apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app"
  labels:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": "app"
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/chart": "component-chart-0.8.6"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "devspace-app"
      "app.kubernetes.io/component": "app"
      "app.kubernetes.io/managed-by": "Helm"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "devspace-app"
        "app.kubernetes.io/component": "app"
        "app.kubernetes.io/managed-by": "Helm"
      annotations:
        "helm.sh/chart": "component-chart-0.8.6"
    spec:
      terminationGracePeriodSeconds: 5
      ephemeralContainers:
      containers:
        - image: "my-image-registry.tld/username/app:c0aca83"
          name: "container-0"
